<a href="https://colab.research.google.com/github/vamshi3686/Deep-Learning/blob/main/ANN_Binary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Sat Mar 28 09:52:47 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   47C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [ ]:
15360/1024

15.0

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [ ]:
df=pd.read_csv("/content/income.csv")
df

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week,income_level
0,39,77516,13,2174,0,40,0
1,50,83311,13,0,0,13,0
2,38,215646,9,0,0,40,0
3,53,234721,7,0,0,40,0
4,28,338409,13,0,0,40,0
...,...,...,...,...,...,...,...
48837,39,215419,13,0,0,36,0
48838,64,321403,9,0,0,40,0
48839,38,374983,13,0,0,50,0
48840,44,83891,13,5455,0,40,0
48841,35,182148,13,0,0,60,1

In [ ]:
df.shape

(48842, 7)

In [ ]:
df.isnull().sum()

age               0
fnlwgt            0
education_num     0
capital_gain      0
capital_loss      0
hours_per_week    0
income_level      0
dtype: int64

In [ ]:
training_data=df.iloc[: 40000, :]
validation_data=df.iloc[40000:45000, : ]
testing_data=df.iloc[45000: ,:]

In [ ]:
training_data.shape

(40000, 7)

In [ ]:
validation_data.shape

(5000, 7)

In [ ]:
testing_data.shape

(3842, 7)

In [ ]:
training_data_inde=training_data.iloc[: , : -1]
training_data_dep=training_data.iloc[ : , -1]

In [ ]:
validation_data_inde=validation_data.iloc[: , :-1]
validation_data_dep=validation_data.iloc[ : , -1]

In [ ]:
testing_data_inde=testing_data.iloc[: , :-1]
testing_data_dep=testing_data.iloc[: ,-1]

**Design the Binary ANN Architecture**

In [ ]:
import tensorflow
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.activations import relu, softmax

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
model= Sequential()
#input layer ti hiden layer 1
model.add(Dense(units=10,
                kernel_initializer='he_uniform',
                activation="relu" ,
                input_dim=training_data_inde.shape[1]))
#hiden layer 1 to hiden layer 2
model.add(Dense(units=4, kernel_initializer="he_uniform", activation="relu"))
#hiden layer 2 to 3
model.add(Dense(units=2, kernel_initializer='he_uniform', activation='relu'))
#hiden layer 3 to output layer
model.add(Dense(units=1, kernel_initializer='glorot_uniform', activation='sigmoid'))

In [ ]:
model.compile(optimizer="adam", loss='binary_crossentropy', metrics=['Accuracy'])

In [ ]:
40000/1000

40.0

In [ ]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 10)             │            70 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 4)              │            44 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 2)              │            10 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 127 (508.00 B)

 Trainable params: 127 (508.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
#training process
model.fit(training_data_inde,
          training_data_dep,
          batch_size=1000,
          epochs=50,
          validation_data=(validation_data_inde,validation_data_dep))

Epoch 1/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - Accuracy: 0.7604 - loss: 0.6435 - val_Accuracy: 0.7674 - val_loss: 0.6382
Epoch 2/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.6365 - val_Accuracy: 0.7674 - val_loss: 0.6313
Epoch 3/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.6300 - val_Accuracy: 0.7674 - val_loss: 0.6248
Epoch 4/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.6239 - val_Accuracy: 0.7674 - val_loss: 0.6187
Epoch 5/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.6182 - val_Accuracy: 0.7674 - val_loss: 0.6129
Epoch 6/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.6129 - val_Accuracy: 0.7674 - val_loss: 0.6076
Epoch 7/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.7604 - loss: 0.6080 - val_Accuracy: 0.7674 - val_loss: 0.6026
Epoch 8/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.6034 - val_Accuracy: 0.7674 - val_loss: 0.5980
Epoch 9/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5991 - val_Accuracy: 0.7674 - val_loss: 0.5937
Epoch 10/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5951 - val_Accuracy: 0.7674 - val_loss: 0.5896
Epoch 11/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5914 - val_Accuracy: 0.7674 - val_loss: 0.5858
Epoch 12/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - Accuracy: 0.7604 - loss: 0.5879 - val_Accuracy: 0.7674 - val_loss: 0.5823
Epoch 13/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - Accuracy: 0.7604 - loss: 0.5847 - val_Accuracy: 0.7674 - val_loss: 0.5791
Epoch 14/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - Accuracy: 0.7604 - loss: 0.5817 - val_Accuracy: 0.7674 - val_loss: 0.5761
Epoch 15/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - Accuracy: 0.7604 - loss: 0.5790 - val_Accuracy: 0.7674 - val_loss: 0.5733
Epoch 16/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - Accuracy: 0.7604 - loss: 0.5765 - val_Accuracy: 0.7674 - val_loss: 0.5706
Epoch 17/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - Accuracy: 0.7604 - loss: 0.5741 - val_Accuracy: 0.7674 - val_loss: 0.5682
Epoch 18/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - Accuracy: 0.7604 - loss: 0.5719 - val_Accuracy: 0.7674 - val_loss: 0.5660
Epoch 19/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - Accuracy: 0.7604 - loss: 0.5699 - val_Accuracy: 0.7674 - val_loss: 0.5640
Epoch 20/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - Accuracy: 0.7604 - loss: 0.5681 - val_Accuracy: 0.7674 - val_loss: 0.5620
Epoch 21/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5664 - val_Accuracy: 0.7674 - val_loss: 0.5603
Epoch 22/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5649 - val_Accuracy: 0.7674 - val_loss: 0.5587
Epoch 23/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5635 - val_Accuracy: 0.7674 - val_loss: 0.5572
Epoch 24/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5622 - val_Accuracy: 0.7674 - val_loss: 0.5558
Epoch 25/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5610 - val_Accuracy: 0.7674 - val_loss: 0.5546
Epoch 26/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5599 - val_Accuracy: 0.7674 - val_loss: 0.5534
Epoch 27/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5589 - val_Accuracy: 0.7674 - val_loss: 0.5524
Epoch 28/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5580 - val_Accuracy: 0.7674 - val_loss: 0.5514
Epoch 29/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5572 - val_Accuracy: 0.7674 - val_loss: 0.5505
Epoch 30/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5565 - val_Accuracy: 0.7674 - val_loss: 0.5497
Epoch 31/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5558 - val_Accuracy: 0.7674 - val_loss: 0.5490
Epoch 32/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5552 - val_Accuracy: 0.7674 - val_loss: 0.5484
Epoch 33/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5547 - val_Accuracy: 0.7674 - val_loss: 0.5477
Epoch 34/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5542 - val_Accuracy: 0.7674 - val_loss: 0.5472
Epoch 35/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5538 - val_Accuracy: 0.7674 - val_loss: 0.5467
Epoch 36/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5534 - val_Accuracy: 0.7674 - val_loss: 0.5463
Epoch 37/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5530 - val_Accuracy: 0.7674 - val_loss: 0.5459
Epoch 38/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5527 - val_Accuracy: 0.7674 - val_loss: 0.5455
Epoch 39/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5525 - val_Accuracy: 0.7674 - val_loss: 0.5452
Epoch 40/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5522 - val_Accuracy: 0.7674 - val_loss: 0.5449
Epoch 41/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5520 - val_Accuracy: 0.7674 - val_loss: 0.5446
Epoch 42/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5518 - val_Accuracy: 0.7674 - val_loss: 0.5444
Epoch 43/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5516 - val_Accuracy: 0.7674 - val_loss: 0.5442
Epoch 44/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5515 - val_Accuracy: 0.7674 - val_loss: 0.5440
Epoch 45/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5514 - val_Accuracy: 0.7674 - val_loss: 0.5438
Epoch 46/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5513 - val_Accuracy: 0.7674 - val_loss: 0.5437
Epoch 47/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5512 - val_Accuracy: 0.7674 - val_loss: 0.5436
Epoch 48/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5511 - val_Accuracy: 0.7674 - val_loss: 0.5434
Epoch 49/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5510 - val_Accuracy: 0.7674 - val_loss: 0.5433
Epoch 50/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.5510 - val_Accuracy: 0.7674 - val_loss: 0.5432

In [ ]:
model.weights

[<Variable path=sequential_1/dense_4/kernel, shape=(6, 10), dtype=float32, value=[[ 0.9334731   0.86676455 -0.6444943   0.163782    0.59976274 -0.02737254
   -0.06484652 -0.52638215  0.29168797 -0.55366254]
  [-0.58171916 -0.20636797 -0.9455352   0.22688249  0.05336658 -0.2886083
    0.23377745  0.1540234  -0.16577601 -0.9075465 ]
  [ 0.5348592  -0.43457723  0.05503941  0.03522424  0.6916252   0.72821903
   -0.2368598  -0.67545915  0.23823762 -0.2587831 ]
  [-0.08481574 -0.44334197 -0.5347588   0.07586423  0.4645466   0.3929324
    0.62702686 -1.0405148  -0.6603365   0.22604227]
  [-0.46468282 -0.6512716   0.8199465   0.9640038   0.21738516  0.70382905
   -0.0326072   0.82956266 -0.6311064  -0.22109127]
  [ 0.50889635 -0.5407829   0.01115298  0.594029    0.00121456  0.4103882
    0.9426002  -0.3895713  -0.24545527 -0.94209194]]>,
 <Variable path=sequential_1/dense_4/bias, shape=(10,), dtype=float32, value=[ 0.          0.          0.          0.06693494  0.044723    0.03920566
  -0.02035135 -0.07502124  0.          0.        ]>,
 <Variable path=sequential_1/dense_5/kernel, shape=(10, 4), dtype=float32, value=[[ 0.4582479  -0.45196822  0.26809597  0.4592433 ]
  [-0.5791031  -0.22252822  0.5111556  -0.24851042]
  [ 0.76068544 -0.0770461   0.7081685  -0.26831514]
  [ 0.3857815  -0.58388776  0.3016991   0.04452167]
  [-0.28992406  0.58322453 -0.40747052  0.57966465]
  [ 0.622306   -0.52663714 -0.08473698  0.41648185]
  [-0.34408066  0.5599524   0.17332703  0.45549828]
  [-0.14001681  0.6533562  -0.14448945 -0.29508516]
  [ 0.58328867 -0.70044637  0.24816597  0.34242618]
  [ 0.4936602   0.27611268  0.44567406  0.6260203 ]]>,
 <Variable path=sequential_1/dense_5/bias, shape=(4,), dtype=float32, value=[-0.05705597 -0.07308277 -0.00115156  0.08788809]>,
 <Variable path=sequential_1/dense_6/kernel, shape=(4, 2), dtype=float32, value=[[ 0.16257872  0.6897671 ]
  [ 0.328527    0.8653099 ]
  [ 0.4265655  -0.7778436 ]
  [-0.899359   -0.72481656]]>,
 <Variable path=sequential_1/dense_6/bias, shape=(2,), dtype=float32, value=[-0.09911203 -0.06083049]>,
 <Variable path=sequential_1/dense_7/kernel, shape=(2, 1), dtype=float32, value=[[-0.81550944]
  [-0.7956554 ]]>,
 <Variable path=sequential_1/dense_7/bias, shape=(1,), dtype=float32, value=[-0.19543737]>]

In [ ]:
if model.predict(np.array([[19,124906,10,0,1719,25]]))[0][0]> 0.5:
  print(1)
else:
  print(0)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
0

In [ ]:
results=model.predict(testing_data_inde)
results

121/121 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

array([[0.2501617],
       [0.2501617],
       [0.2501617],
       ...,
       [0.2501617],
       [0.2501617],
       [0.2501617]], dtype=float32)

In [ ]:
c=[]
for i[0] in results:
  if i>0.5:
    c.append(1)
  else:
    c.append(0)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [ ]:
confusion_matrix(testing_data_dep,c)

array([[2902,    0],
       [ 940,    0]])

In [ ]:
accuracy_score(testing_data_dep,c)

0.7553357626236336

In [ ]:
print(classification_report(testing_data_dep, c))

              precision    recall  f1-score   support

           0       0.76      1.00      0.86      2902
           1       0.00      0.00      0.00       940

    accuracy                           0.76      3842
   macro avg       0.38      0.50      0.43      3842
weighted avg       0.57      0.76      0.65      3842